version: '2'

# consolidate the 12 images into 2
# consolidate the 12 containers into 5

services:
  n64:
    build:
      context: .
      dockerfile: main/Dockerfile
    networks:
      - net
    ports:
      - "8080:8080"

networks:
  net:
